umbraco/Components/SearchFormViewComponent.cs
using Microsoft.AspNetCore.Mvc;

using umbraco.Models.Search;

namespace umbraco.Components;

[ViewComponent(Name = "SearchForm")]
public class SearchFormViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(SearchRequestModel model)
    {
 
        return View(model);
    }
}

umbraco/Controllers/Render/SearchPageController.cs
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Web.Common.Controllers;
using umbraco.Models.ContentModels;
using umbraco.Models.Search;
using umbraco.Models.ViewModels;
using umbraco.Services;
using umbraco.Helpers;

namespace umbraco.Controllers.Render;

public class SearchPageController(ILogger<RenderController> logger,
    ICompositeViewEngine compositeViewEngine, IUmbracoContextAccessor umbracoContextAccessor,
    IHttpContextAccessor httpContextAccessor, ISearchService searchService) : RenderController(logger, compositeViewEngine, umbracoContextAccessor)
{

    public override IActionResult Index()
    {
        var _httpContext = httpContextAccessor.HttpContext;
        var query = _httpContext.Request.Query["query"];
        var page=_httpContext.Request.Query["page"];
        var pagesize = 1;

        var _searchrequest = new SearchRequestModel(query, page, pagesize);
        var searchresponse = searchService.Search(_searchrequest);
        var pagination= new PaginationViewModel
        {
            TotalResults = searchresponse.TotalResultCount,
            TotalPages = (int)Math.Ceiling((double)searchresponse.TotalResultCount / _searchrequest.PageSize),
            ResultsPerPage = _searchrequest.PageSize,
            CurrentPage=_searchrequest.Page,
            PaginationUrlFormat = PaginationHelper.GetPaginationUrlFormat(Request.Path, Request?.QueryString.ToString(), page)
        };

        var model = new SearchPageContentModel(CurrentPage)
        {
            SearchRequest = _searchrequest,
            SearchResponse = searchresponse,
            Pagination = pagination
        }; 
        return CurrentTemplate(model);
    }
}

umbraco/Views/ContentPage.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<Umbraco.Cms.Web.Common.PublishedModels.ContentPage>
@using Umbraco.Cms.Web.Common.PublishedModels;
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
    Layout = "Main.cshtml";
  }
  
@await Html.GetBlockGridHtmlAsync(Model, "headerContent")
@await Html.GetBlockGridHtmlAsync(Model, "mainContent")

umbraco/Views/Home.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.Home>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
    Layout = "main.cshtml";
}
<!-- Main -->
@await Html.GetBlockGridHtmlAsync(Model, "headerContent")
@await Html.GetBlockGridHtmlAsync(Model, "mainContent")

umbraco/Views/SearchPage.cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@using umbraco.Models.ContentModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<SearchPageContentModel>;
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
    Layout = "Main.cshtml";
}
<div style="padding-left: 3%;">
    @await Component.InvokeAsync("SearchForm", new { Model?.SearchRequest })
    <div style="display:flex">
        <div><h3>Searching for: @Model.SearchRequest.Query </h3>
        </div>
        <div>
        @if (Model.SearchResponse.HasResults)
        {
            <div class="table-wrapper" style="margin-left:100%; width: 500%;">
                <table>
                    <tbody>
                        @foreach (var item in Model.SearchResponse.SearchResults)
                        {
                            var contentItem = Umbraco.Content(item.Id);
                            <tr>
                                <td><a href="@contentItem.Url()">@contentItem.Name</a></td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
           
        </div>

    </div>        @await Component.InvokeAsync("PaginationView", new { model = Model.Pagination })
</div>

umbraco/Views/main.cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@using Umbraco.Cms.Web.Common.PublishedModels;


@{
	Layout = null;
}

<!DOCTYPE HTML>

<html>
	<head>
    @await Html.PartialAsync("metaData")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
      <noscript><link rel="stylesheet" href="/css/noscript.css" /></noscript>
	</head>
	<body class="is-preload">
		<!-- Wrapper -->
			<div id="wrapper">
		@await Html.PartialAsync("header")
		@RenderBody()
		<!-- Footer-->
		@await Html.PartialAsync("footer")
        @await Html.PartialAsync("menu")
</div>
		<!-- Scripts -->
    <script src="/scripts/js/jquery.min.js"></script>
    <script src="/scripts/js/browser.min.js"></script>
    <script src="/scripts/js/breakpoints.min.js"></script>
    <script src="/scripts/js/util.js"></script>
	<script src="/scripts/js/main.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.3.2/lazysizes.min.js" integrity="sha512-q583ppKrCRc7N5O0n2nzUiJ+suUv7Et1JGels4bXOaMFQcamPk9HjdUknZuuFjBNs7tsMuadge5k9RzdmO+1GQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script> 
        window.addEventListener('beforeunload', function () {
            sessionStorage.setItem('scrollPosition', window.scrollY);
        }); 
        window.addEventListener('DOMContentLoaded', function () {
            var scrollPosition = sessionStorage.getItem('scrollPosition');
            if (scrollPosition) {
                window.scrollTo(0, parseInt(scrollPosition));
            }
        });
    </script>



</body>
</html> 